# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb64624ca08dfd2d4803b2687317ee21c5d688543e18669024565d1c0746af8213067868cd6e10ba952e5074420d8e679275d1eab6d6f9f9f6205e4e603c37e

test:
  secret_key_base: 8dc9e47d726e569aa900250ad526f6b564baa0a83d5ba4c0c11cce09c2cf23612232bd4565261ef462032fb5758dd1618cc566e8cc9f411fb34bd57b3a12c0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
